"""add validation

Revision ID: 190664f4a2b0
Revises: 6c2ce31f4c15
Create Date: 2020-09-01 14:49:37.548691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190664f4a2b0'
down_revision = '6c2ce31f4c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('validation', sa.Enum('no_result', 'valid', 'invalid', 'timeout', 'unknown', 'error', name='validationenum'), nullable=True),
    sa.Column('stdout', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_result')
    # ### end Alembic commands ###
