"""v1

Revision ID: 2a5b0607d2bd
Revises: 
Create Date: 2020-09-14 12:38:40.050359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5b0607d2bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission', sa.Enum('invalid_perm', 'read', 'upload_benchmark', 'upload_solver', 'message_queue', 'start_run', 'post_results', 'change_password', 'change_other_password', 'admin_user', name='permissionenum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    # ### end Alembic commands ###
