"""add default solver args

Revision ID: 6757ddf93a55
Revises: 3b9560d68ad7
Create Date: 2020-07-24 13:40:57.007660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6757ddf93a55'
down_revision = '3b9560d68ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solver', sa.Column('default_arguments', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solver', 'default_arguments')
    # ### end Alembic commands ###
