"""v1

Revision ID: d94f5302b820
Revises: 
Create Date: 2020-09-09 16:08:30.911117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94f5302b820'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('solver_id', sa.Integer(), nullable=True),
    sa.Column('arguments', sa.String(length=1024), nullable=True),
    sa.Column('performance', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark.id'], ),
    sa.ForeignKeyConstraint(['solver_id'], ['solver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('no_result', 'sat', 'unsat', 'timeout', 'unknown', 'error', name='solverresponseenum'), nullable=True),
    sa.Column('stdout', sa.UnicodeText(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instance.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('solver_id', sa.Integer(), nullable=True),
    sa.Column('validation', sa.Enum('no_result', 'valid', 'invalid', 'timeout', 'unknown', 'error', name='validationenum'), nullable=True),
    sa.Column('stdout', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], ),
    sa.ForeignKeyConstraint(['solver_id'], ['solver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_result')
    op.drop_table('result')
    op.drop_table('run')
    # ### end Alembic commands ###
