"""instances table

Revision ID: f9fb55ac3467
Revises: a83f25b66f65
Create Date: 2020-07-22 12:24:31.101157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fb55ac3467'
down_revision = 'a83f25b66f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance')
    # ### end Alembic commands ###
